### ISSUE TITLE
Gracias!

### ISSUE THREAD

**Issue by xbelanch** [hcosta/cpu-3d-graphics#1]
Hola!

No, no és un "issue". Simplemente felicitarte por el magnífico tutorial "Apuntes de Gráficos 3D" que he seguido con muchísimo entusiasmo. Comparto mi "crab" :-) como reconocimiento a tu trabajo.

Gracias!

![nanorender](https://github.com/user-attachments/assets/5c44f875-6289-4129-a1ab-8cb8f3122960)

**Comment by hcosta** [comment]
Ohh!! Me alegro de que te haya servido @xbelanch!! Aprendí muchísimo realizando estos apuntes, seguro que muchas cosas se pueden mejorar pero ahí queda la aportación 😉
